#pragma once

#include <ntddk.h>

#define HV_START	CTL_CODE(FILE_DEVICE_UNKNOWN, 0xF9000, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define HV_STOP		CTL_CODE(FILE_DEVICE_UNKNOWN, 0xF9001, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define HV_STATUS	CTL_CODE(FILE_DEVICE_UNKNOWN, 0xF9002, METHOD_BUFFERED, FILE_ANY_ACCESS)

NTSTATUS handle_call(PDEVICE_OBJECT device_object, PIRP irp);
NTSTATUS create_call(PDEVICE_OBJECT device_object, PIRP irp);
NTSTATUS close_call(PDEVICE_OBJECT device_object, PIRP irp);